name: Publish with lerna

on:
  watch:
    types: [started]
  

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: npm install
    - run: npm run lerna -- changed
